server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: businessdomain-user
          uri: lb://businessdomain-user
          predicates:
            - Path=/user/V1/**
          filters:
            - AuthFilter
        - id: businessdomain-song
          uri: lb://businessdomain-song
          predicates:
            - Path=/playlist/V1/**
          filters:
            - AuthFilter
        - id: businessdomain-pub
          uri: lb://businessdomain-pub
          predicates:
            - Path=/pub/V1/**
          filters:
            - AuthFilter
        - id: businessdomain-auth
          uri: lb://businessdomain-auth
          predicates:
            - Path=/auth/V1/**
